version: '3.8'
services:
  post_db:
    image: ${DB_IMAGE}
    volumes:
      - ${DB_DATA_PATH}:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${UI_IMAGE}
    ports:
      - "${UI_EXTERNAL_PORT}:9292/tcp"
    networks:
      reddit_front:
        aliases:
          - ui
  post:
    build: ./post-py
    image: ${POST_IMAGE}
    networks:
      reddit_back:
        aliases:
          - post
      reddit_front:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${COMMENT_IMAGE}
    networks:
      reddit_back:
        aliases:
          - comment
      reddit_front:
        aliases:
          - comment

networks:
  reddit_front:
  reddit_back:
